name: VaultLite
version: ${project.version}
description: VaultLite: API Vault moderna com LuckPerms e PlaceholderAPI.
authors: [VaultLite]
website: https://github.com/your-org/VaultLite
api-version: 1.20

main: ${mainClass}
load: startup

provides: [Vault]

softdepend: [LuckPerms, PlaceholderAPI]