name: VaultLite
version: ${version}
description: "VaultLite: API Vault moderna com LuckPerms e PlaceholderAPI."
authors: [VaultLite]
website: https://github.com/your-org/VaultLite
api-version: 1.20

main: net.milkbowl.vault.Vault
load: startup

provides: [Vault]

softdepend: [LuckPerms, PlaceholderAPI]


